/* eslint-disable no-unused-vars */
const destinations = [
  { name: "Anguilla", regulier: false },
  { name: "Antigua", regulier: false },
  { name: "Bequia", regulier: false },
  { name: "Canouan", regulier: false },
  { name: "Carriacou", regulier: false },
  { name: "Dominique", regulier: false },
  { name: "Republique Dominicaine", regulier: false },
  { name: "Grenade", regulier: false },
  { name: "Guadeloupe", regulier: true },
  { name: "Martinique", regulier: false },
  { name: "Mustique", regulier: false },
  { name: "Nevis", regulier: false },
  { name: "Puerto-Rico", regulier: false },
  { name: "St Barth", regulier: true },
  { name: "St Croix", regulier: false },
  { name: "St Eustatius", regulier: false },
  { name: "St Kitts", regulier: false },
  { name: "St Lucia", regulier: false },
  { name: "St Maarteen", regulier: true },
  { name: "St Thomas", regulier: false },
  { name: "St Vincent", regulier: false },
  { name: "Tortola BVI", regulier: false },
  { name: "Union Island", regulier: false },
  { name: "Vieques", regulier: false },
]
